[package]
name = "noplan"
version = "0.1.0"
edition = "2021"
authors = ["Marco Schmidt <marco.schmidt@taugamma.eu>"]

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[profile.release]
# lto = true
debug=true

[[bin]]
name = "kernal"
path = "src/kernal.rs"
